# Generated by Django 3.2.8 on 2021-10-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='user',
        ),
    ]
