# Generated by Django 3.2.8 on 2021-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0002_auto_20211011_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='experiencereaction',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_arrival',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='scheduled_departure',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='flightreaction',
            name='timestamp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.CharField(max_length=30),
        ),
    ]
