# Generated by Django 3.2.8 on 2021-10-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0003_auto_20211012_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='tripadvisor_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='website_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
