# Generated by Django 3.2.8 on 2021-10-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0004_auto_20211013_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='cuisine',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
