# Generated by Django 3.2.8 on 2021-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0005_experience_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
