# Generated by Django 3.2.8 on 2021-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oystercard', '0006_experience_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='ranking',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
