export const UPDATE_TRIP_ID = 'UPDATE_TRIP_ID';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const UPDATE_TRIP_DETAILS = 'UPDATE_TRIP_DETAILS';
export const UPDATE_TRIP = 'UPDATE_TRIP';
export const ADD_FLIGHT = 'ADD_FLIGHT';
export const ADD_HOTEL = 'ADD_HOTEL';
export const ADD_RESTAURANT = 'ADD_RESTAURANT';
export const ADD_ATTRACTION = 'ADD_ATTRACTION';
